# Generated by Django 5.2.9 on 2025-12-30 19:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('company_name', models.CharField(max_length=120)),
                ('bus_type', models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP'), ('vvip', 'VVIP')], default='normal', max_length=20)),
                ('total_seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('amenities', models.TextField(blank=True, help_text='WiFi, Charger, AC, TV, reclining seats, snacks etc.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['company_name', 'plate_number'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Places',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_hours', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_to', to='core.place')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_from', to='core.place')),
            ],
            options={
                'ordering': ['origin__name', 'destination__name'],
                'unique_together': {('origin', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1000)])),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('on_going', 'On Going'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('available_seats', models.PositiveIntegerField(default=0)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='core.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='core.route')),
            ],
            options={
                'ordering': ['-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('is_booked', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.trip')),
            ],
            options={
                'ordering': ['seat_number'],
                'unique_together': {('trip', 'seat_number')},
            },
        ),
    ]
