# Generated by Django 5.2.9 on 2026-01-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bus_amenities_alter_trip_arrival_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
