# Generated by Django 5.2.9 on 2026-01-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='airtel_merchant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='halopesa_merchant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='merchant_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Namba ya Biashara (Merchant)'),
        ),
        migrations.AddField(
            model_name='bus',
            name='mixx_merchant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='reference_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Kumbukumbu Namba (Reference)'),
        ),
        migrations.AddField(
            model_name='bus',
            name='vodacom_merchant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
