# Generated by Django 5.2.9 on 2026-01-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('core', '0003_seat_blocked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='core.seat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Inasubiri Malipo'), ('confirmed', 'Imethibitishwa'), ('cancelled', 'Imeghairiwa'), ('expired', 'Imeisha Muda')], default='pending', max_length=20),
        ),
    ]
