# Generated by Django 5.2.9 on 2026-01-20 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_seats_alter_booking_status'),
        ('core', '0004_booking_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_passengers', to='core.seat'),
        ),
    ]
